apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-ryanmc-net-tls
spec:
  secretName: k8s-ryanmc-net
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.ryanmc.net
  dnsNames:
    - k8s.ryanmc.net
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s.ryanmc.net

  